site_name: "ra-mcp"
# site_url: https://ai-riksarkivet.github.io/ra-mcp/latest/
site_author: "AI Riksarkivet"
site_description: "MCPs for Riksarkivet's APIs"
repo_name: AI-Riksarkivet/ra-mcp
# repo_url: https://github.com/AI-Riksarkivet/ra-mcp/
# edit_uri: https://github.com/AI-Riksarkivet/ra-mcp/tree/main/docs

use_directory_urls: false

extra:
  generator: false
  version:
    provider: mike
  social:
    - icon: boostrap/hf-logo-pirate
      link: https://huggingface.co/Riksarkivet
      name: Hugging Face
    - icon: fontawesome/brands/github
      link: https://github.com/AI-Riksarkivet
      name: Github 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/national-archives-in-sweden-riksarkivet-
      name: Linkedin 
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ra-mcp/
      name: PyPi
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/airiksarkivet
      name: Docker Hub 
  analytics:
    provider: custom
    property: matomo

extra_css:
  - stylesheets/extra.css


theme:
  name: material
  custom_dir: docs/overrides


  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - toc.follow


  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  favicon: https://raw.githubusercontent.com/AI-Riksarkivet/htrflow/main/docs/assets/favicon.ico
  logo: https://raw.githubusercontent.com/AI-Riksarkivet/htrflow/main/docs/assets/riks.png
  icon:
    logo: logo
    repo: fontawesome/brands/github


plugins:
  - tags
  - search
  - marimo:
      enabled: true
      display_code: false
      display_output: true
      is_reactive: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/ra_mcp]
          options:
            merge_init_into_class: True
            show_signature: False
            show_symbol_type_heading: True
            show_symbol_type_toc: True
            show_root_toc_entry: True
            show_root_heading: True
            show_root_full_path: False
            show_source: True
            show_category_heading: False
            show_bases: True
            filters:
              - "!^_"
              - "^_predict$"
  # - git-revision-date-localized
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

nav:
  - ra-mcp: index.md
  - 🚀 Getting started :
    - Installation: getting_started/installation.md
    - Quickstart: getting_started/quick_start.md
  - Tutorials: notebooks/test.py